// TODO: SETUP SERVER, CONSTANTS
// TODO: SETUP LOGGER ON UNHANDLED REJECTION
// TODO: SETUP LOGGER ON EVERY REQUEST USING MORGAN WITH EXPRESS APP
import dotenv from 'dotenv';

// Using .env
dotenv.config();
